### PR TITLE
SQL Server 2014 package

### PR DESCRIPTION
**Pull request by JonCubed**

### CODE REVIEW

**Comment by neutmute** [comment]
nice! let me know when this is final and I'll publish to myget

**Comment by JonCubed** [comment]
this is final

**Comment by neutmute** [comment]
Forgot this is already automatically built when merged to master.
https://www.myget.org/F/nm-chocolatey-packs/api/v2

Choco official won't accept SQL packages because the ISO is not publicly available
See https://github.com/neutmute/nm-boxstarter/blob/master/base-box.ps1 for example where myget sourced package is used

**Comment by neutmute** [comment]
nice work btw!

**Pull request merged**
